betterWorld/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from Portfolio import views as portfolio_views
from blogs import views as blogs_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', portfolio_views.home, name = 'home'),
    path('blogs/', include('blogs.urls'))   

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogs/urls.py
from django.contrib import admin
from django.urls import path

from Portfolio import views as portfolio_views
from blogs import views as blogs_views

app_name = 'blogs'

urlpatterns = [
    
    path('', blogs_views.blog_home, name = 'all_blogs'),
    path('<int:blog_id>/', blogs_views.blog_detail, name = 'blog_detail')

]

PaintGreen/models.py
from django.db import models

# Create your models here.

Portfolio/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=60)
    photo = models.ImageField(upload_to='portfolio/images',default='portfolio/images/Watch-this-space.jpg')
    url = models.URLField(blank = True)

    def __str__(self):
    	return self.title

blogs/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
	"""docstring for ClassName"""
	topic = models.CharField(max_length=30)
	blog_description = models.CharField(max_length=60)
	blog_post_date = models.DateField()

	def __str__(self):
		return self.topic

cleanIt/models.py
from django.db import models

# Create your models here.

eduSupport/models.py
from django.db import models

# Create your models here.

elderlySupport/models.py
from django.db import models

# Create your models here.

PaintGreen/views.py
from django.shortcuts import render

# Create your views here.

Portfolio/views.py
from django.shortcuts import render

# Create your views here.
from .models import Project

def home(request):
	projects = Project.objects.all()
	return render(request, 'Portfolio/home.html', {'Projects' : projects})

blogs/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from .models import Blog

def blog_home(request):
	blogs = Blog.objects.all()
	return render(request, 'blogs/blog_home.html', {'Blogs': blogs})

def blog_detail(request, blog_id):
	blog = get_object_or_404(Blog, pk = blog_id)
	return render(request, 'blogs/blog_detail.html', {'Blog': blog})

cleanIt/views.py
from django.shortcuts import render

# Create your views here.

eduSupport/views.py
from django.shortcuts import render

# Create your views here.

elderlySupport/views.py
from django.shortcuts import render

# Create your views here.

Portfolio/templates/Portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <title>A Better World | Home</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'Portfolio/customCss.css' %}">

    

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              
              <li class="nav-item">
                <a class="nav-link" href="{% static 'Portfolio/dummy.pdf' %}">Our Vision</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}#projectsundertaken">Our Projects</a>
              </li>

              
              <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Our Projects
                </a>

                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li>


                    {% for project in Projects %}
                    <a class="dropdown-item" href="{{ project.url }}"> {{ project.title }}</a>
                    <li><hr class="dropdown-divider"></li>
                    {% endfor %}
                    <!-- <a class="dropdown-item" href="#">Action</a>
                  </li>
                  
                </ul> -->
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blogs:all_blogs' %}">Blogs</a>
              </li>  
              
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
    </nav>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    
    </nav>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}

            {% endblock %}
            </div>
        </div>
    </div>
  </body>
</html>

Portfolio/templates/Portfolio/home.html
{% extends 'Portfolio/base.html' %}

{% block content %}



	{% load static %}
	<br>
	<div class="page-header">
		<h2>Hey, such a beautiful world, isn't it? Let's  work together to make it better.</h2>
	</div>

	<div class="home-image">

		<img src= "{% static 'Portfolio/HomeImage/pexels-quang-nguyen-vinh-2132180_mountain.jpg' %}" width="1080" height="480" >
		<!-- <video autoplay= "autoplay"  loop = "loop"  width="1080" height="450">
			<source src="{% static 'Portfolio/HomeImage/Foggy_river_drone.mp4' %}" type="video/mp4">
		  
		</video> -->
	</div>
	
	<br>

	<div class="content container">
		<div class="row">
			<h1><a id="projectsundertaken">Projects undertaken</a></h1>
			{% for project in Projects %}

			<h2>{{ project.id }}. {{ project.title }}</h2>
			</br>
			<p>{{ project.description }}</p>
			<a href = "{{ project.url }}"> <img src="{{ project.photo.url }}" width="250" height="250"> </a>

		{% endfor %}
		</div>
	</div>

{% endblock %}

blogs/templates/blogs/blog_detail.html
<h2>{{ Blog.topic }}</h2>
<p>{{ Blog.blog_description }}</p>

blogs/templates/blogs/blog_home.html
{% extends 'Portfolio/base.html' %}

{% block content %}

<h2>Rahul has written {{ Blogs.count }} blog{{ Blogs.count|pluralize }} : </h2>
{% for blog in Blogs %}


<a href = "{% url 'blogs:blog_detail' blog.id  %}">  
 <h2>{{ blog.id }}. {{ blog.topic }}</h2>
</a>
<p>Posted on: {{ blog.blog_post_date }}</p>
<p>{{ blog.blog_description|truncatechars:5 }}</p>
<br>

{% endfor %}

{% endblock %}